import type {
  ActivityEntry,
  Entity,
  Relationship,
  Scenario,
  Workspace,
} from "../domain/model";

const at = "2026-08-31T09:00:00.000Z";
const activity = (workspace: string): ActivityEntry[] => [
  {
    id: `${workspace}-a1`,
    action: "WORKSPACE_SEEDED",
    detail: "Fictional demo template loaded.",
    actor: "system",
    at,
    version: 1,
  },
  {
    id: `${workspace}-a2`,
    action: "MAP_REVIEWED",
    detail: "Declared facts remain separate from human attestations.",
    actor: "system",
    at,
    version: 1,
  },
];

const e = (
  id: string,
  name: string,
  type: Entity["type"],
  trust: Entity["trust"],
  critical = false,
  description = "",
  metadata?: Entity["metadata"],
): Entity => ({
  id,
  name,
  type,
  trust,
  critical,
  description,
  ...(metadata ? { metadata } : {}),
});

const r = (
  id: string,
  from: string,
  to: string,
  type: Relationship["type"],
  group: string,
  label: string,
  trust: Relationship["trust"] = "VERIFIED",
): Relationship => ({
  id,
  from,
  to,
  type,
  group,
  label,
  trust,
});

const s = (
  id: string,
  name: string,
  unavailableEntityIds: string[],
  durationDays: number,
  context: string,
): Scenario => ({
  id,
  name,
  unavailableEntityIds,
  durationDays,
  context,
  createdBy: "system",
});

const appStudio: Workspace = {
  id: "demo-studio",
  slug: "northstar-studio",
  name: "Diamond Apps",
  tagline: "Three apps. One founder-shaped gap.",
  sector: "studio",
  fictional: true,
  cover: "/assets/demo-studio.webp",
  version: 1,
  entities: [
    e(
      "studio-founder",
      "Theo Mercer",
      "person",
      "VERIFIED",
      true,
      "Founder and only Apple account holder.",
    ),
    e(
      "studio-ops",
      "Maya Chen",
      "person",
      "VERIFIED",
      false,
      "Operations lead and release coordinator.",
    ),
    e(
      "studio-support-owner",
      "Lina Brooks",
      "person",
      "VERIFIED",
      false,
      "Customer support owner.",
    ),
    e(
      "studio-phone",
      "Theo’s personal phone",
      "device",
      "VERIFIED",
      true,
      "Receives the only trusted-device prompt.",
      {
        requiresPersonalDevice: true,
        lastVerifiedAt: "2026-08-14",
        verificationStatus: "VERIFIED",
      },
    ),
    e(
      "studio-apple-account",
      "Apple developer account",
      "account",
      "DECLARED",
      true,
      "Personal enrollment controls store actions.",
      {
        requiresPersonalEmail: true,
        recoveryMethodExists: true,
        secondaryOwner: "",
        verificationStatus: "DECLARED",
      },
    ),
    e(
      "studio-appstore",
      "App Store Connect",
      "service",
      "VERIFIED",
      true,
      "Product releases and listing updates.",
    ),
    e(
      "studio-cert",
      "Production signing certificate",
      "recovery-mechanism",
      "STALE",
      true,
      "Expires in 18 days.",
      {
        lastVerifiedAt: "2026-04-11",
        verificationStatus: "STALE",
        documentationExists: false,
      },
    ),
    e(
      "studio-github",
      "GitHub organization",
      "service",
      "VERIFIED",
      true,
      "Source and release tags.",
    ),
    e(
      "studio-ci",
      "Build pipeline",
      "service",
      "VERIFIED",
      true,
      "Builds signed release artifacts.",
    ),
    e(
      "studio-host",
      "Cloud hosting",
      "vendor",
      "DECLARED",
      true,
      "API and customer web properties.",
    ),
    e(
      "studio-dns",
      "Domain and DNS",
      "service",
      "VERIFIED",
      true,
      "Registrar and authoritative DNS.",
    ),
    e(
      "studio-support",
      "Support inbox",
      "communication-channel",
      "VERIFIED",
      true,
      "Shared customer-support queue.",
    ),
    e(
      "studio-status",
      "Incident channel",
      "communication-channel",
      "UNKNOWN",
      false,
      "Status updates share production hosting.",
      { documentationExists: false },
    ),
    e(
      "studio-recovery-doc",
      "Release recovery note",
      "document",
      "UNKNOWN",
      false,
      "Draft note stored beside release credentials.",
      { storageLocationCategory: "same-system", documentationExists: true },
    ),
    e(
      "studio-release",
      "Ship an app update",
      "workflow",
      "VERIFIED",
      true,
      "Build, sign, and publish an urgent release.",
    ),
    e(
      "studio-support-workflow",
      "Answer customer support",
      "workflow",
      "VERIFIED",
      true,
      "Read, triage, and respond to customers.",
    ),
    e(
      "studio-incident",
      "Publish incident communication",
      "workflow",
      "DECLARED",
      true,
      "Communicate during a service incident.",
    ),
  ],
  relationships: [
    r(
      "st-r1",
      "studio-release",
      "studio-github",
      "depends-on",
      "source",
      "source",
    ),
    r("st-r2", "studio-release", "studio-ci", "depends-on", "build", "build"),
    r(
      "st-r3",
      "studio-release",
      "studio-cert",
      "depends-on",
      "signing",
      "sign",
    ),
    r(
      "st-r4",
      "studio-release",
      "studio-appstore",
      "depends-on",
      "publish",
      "publish",
    ),
    r(
      "st-r5",
      "studio-ci",
      "studio-github",
      "depends-on",
      "source",
      "checkout",
    ),
    r(
      "st-r6",
      "studio-cert",
      "studio-apple-account",
      "administered-by",
      "account",
      "renewed through",
    ),
    r(
      "st-r7",
      "studio-appstore",
      "studio-apple-account",
      "accessible-by",
      "account",
      "signed in through",
    ),
    r(
      "st-r8",
      "studio-apple-account",
      "studio-founder",
      "owned-by",
      "access",
      "owned by",
    ),
    r(
      "st-r9",
      "studio-apple-account",
      "studio-phone",
      "recovers-via",
      "authentication",
      "authenticates with",
    ),
    r(
      "st-r10",
      "studio-apple-account",
      "studio-recovery-doc",
      "recovers-via",
      "procedure",
      "documented in",
      "UNKNOWN",
    ),
    r(
      "st-r11",
      "studio-support-workflow",
      "studio-support",
      "communicates-through",
      "inbox",
      "uses",
    ),
    r(
      "st-r12",
      "studio-support",
      "studio-support-owner",
      "accessible-by",
      "access",
      "managed by",
    ),
    r(
      "st-r13",
      "studio-incident",
      "studio-status",
      "communicates-through",
      "channel",
      "publishes through",
    ),
    r(
      "st-r14",
      "studio-status",
      "studio-host",
      "depends-on",
      "runtime",
      "runs on",
    ),
    r(
      "st-r15",
      "studio-host",
      "studio-dns",
      "depends-on",
      "routing",
      "routed by",
    ),
    r(
      "st-r16",
      "studio-host",
      "studio-ops",
      "administered-by",
      "access",
      "managed by",
    ),
  ],
  scenarios: [
    s(
      "studio-founder-away",
      "Founder away, phone unreachable",
      ["studio-founder", "studio-phone"],
      7,
      "An urgent release is needed within 24 hours while the founder cannot receive authentication prompts.",
    ),
    s(
      "studio-hosting-outage",
      "Hosting and status share a failure",
      ["studio-host"],
      1,
      "Production hosting is unavailable during an incident.",
    ),
  ],
  proposals: [],
  activity: activity("studio"),
};

const edtech: Workspace = {
  id: "demo-edtech",
  slug: "cedar-classroom",
  name: "Study Top",
  tagline: "Exam day without the usual front door.",
  sector: "education",
  fictional: true,
  cover: "/assets/demo-edtech.webp",
  version: 1,
  entities: [
    e(
      "edu-ops",
      "Nadia Okafor",
      "person",
      "VERIFIED",
      true,
      "Operations lead who wrote the emergency procedure.",
    ),
    e(
      "edu-support",
      "Sam Patel",
      "person",
      "DECLARED",
      false,
      "Student support coordinator.",
    ),
    e(
      "edu-sso",
      "Identity provider",
      "service",
      "VERIFIED",
      true,
      "Primary sign-in for staff and students.",
    ),
    e(
      "edu-lms",
      "Learning platform",
      "service",
      "VERIFIED",
      true,
      "Course delivery and exams.",
    ),
    e(
      "edu-content",
      "Course content storage",
      "service",
      "VERIFIED",
      true,
      "Lessons and assessment packages.",
    ),
    e(
      "edu-video",
      "Video classroom vendor",
      "vendor",
      "DECLARED",
      false,
      "Live teaching sessions.",
    ),
    e(
      "edu-admin",
      "Teacher administration",
      "account",
      "VERIFIED",
      true,
      "Roster and course controls.",
    ),
    e(
      "edu-emergency",
      "Emergency local access",
      "recovery-mechanism",
      "STALE",
      true,
      "Break-glass account, not tested this term.",
      { lastVerifiedAt: "2026-02-12", verificationStatus: "STALE" },
    ),
    e(
      "edu-procedure",
      "Emergency access procedure",
      "document",
      "DECLARED",
      true,
      "Steps known well by one employee.",
      { documentationExists: true, storageLocationCategory: "internal-docs" },
    ),
    e(
      "edu-billing",
      "School billing",
      "workflow",
      "VERIFIED",
      false,
      "Invoice schools and reconcile seats.",
    ),
    e(
      "edu-exam",
      "Run scheduled assessment",
      "workflow",
      "VERIFIED",
      true,
      "Authenticate students and deliver an exam.",
    ),
    e(
      "edu-teacher-help",
      "Resolve teacher access",
      "workflow",
      "DECLARED",
      true,
      "Restore a teacher during class.",
    ),
    e(
      "edu-student-help",
      "Answer student support",
      "workflow",
      "VERIFIED",
      true,
      "Shared student support queue.",
    ),
    e(
      "edu-support-inbox",
      "Student support inbox",
      "communication-channel",
      "VERIFIED",
      true,
      "Shared queue outside the SSO tenant.",
    ),
  ],
  relationships: [
    r("ed-r1", "edu-exam", "edu-lms", "depends-on", "delivery", "delivered by"),
    r(
      "ed-r2",
      "edu-exam",
      "edu-sso",
      "depends-on",
      "identity",
      "authenticates with",
    ),
    r("ed-r3", "edu-lms", "edu-content", "depends-on", "content", "loads from"),
    r(
      "ed-r4",
      "edu-admin",
      "edu-sso",
      "depends-on",
      "identity",
      "authenticates with",
    ),
    r(
      "ed-r5",
      "edu-teacher-help",
      "edu-admin",
      "depends-on",
      "admin",
      "requires",
    ),
    r(
      "ed-r6",
      "edu-teacher-help",
      "edu-emergency",
      "recovers-via",
      "emergency",
      "can recover through",
    ),
    r(
      "ed-r7",
      "edu-emergency",
      "edu-procedure",
      "depends-on",
      "procedure",
      "described in",
    ),
    r(
      "ed-r8",
      "edu-procedure",
      "edu-ops",
      "accessible-by",
      "knowledge",
      "known by",
    ),
    r(
      "ed-r9",
      "edu-student-help",
      "edu-support-inbox",
      "communicates-through",
      "inbox",
      "uses",
    ),
    r(
      "ed-r10",
      "edu-support-inbox",
      "edu-support",
      "accessible-by",
      "access",
      "owned by",
    ),
    r(
      "ed-r11",
      "edu-billing",
      "edu-admin",
      "depends-on",
      "roster",
      "reads seats from",
    ),
    r("ed-r12", "edu-video", "edu-sso", "depends-on", "identity", "uses SSO"),
  ],
  scenarios: [
    s(
      "edu-sso-exam",
      "SSO unavailable during exams",
      ["edu-sso", "edu-ops"],
      1,
      "The identity provider is down and the only person fluent in the emergency procedure is unavailable.",
    ),
  ],
  proposals: [],
  activity: activity("edtech"),
};

const restaurant: Workspace = {
  id: "demo-restaurant",
  slug: "ember-table",
  name: "One Evening",
  tagline: "Dinner service when the screens go quiet.",
  sector: "hospitality",
  fictional: true,
  cover: "/assets/demo-restaurant.webp",
  version: 1,
  entities: [
    e(
      "rest-manager",
      "Iris Romero",
      "person",
      "VERIFIED",
      true,
      "Only manager who has rehearsed offline service.",
    ),
    e(
      "rest-floor",
      "Noah Williams",
      "person",
      "DECLARED",
      false,
      "Floor lead at the busiest location.",
    ),
    e(
      "rest-pos",
      "Point of sale",
      "service",
      "VERIFIED",
      true,
      "Orders and checks across three locations.",
    ),
    e(
      "rest-payments",
      "Payment processor",
      "vendor",
      "VERIFIED",
      true,
      "Card authorization.",
    ),
    e(
      "rest-reservations",
      "Reservations",
      "service",
      "DECLARED",
      false,
      "Guest bookings and waitlist.",
    ),
    e(
      "rest-schedule",
      "Staff scheduling",
      "service",
      "VERIFIED",
      false,
      "Shift roster and coverage.",
    ),
    e(
      "rest-suppliers",
      "Supplier ordering inbox",
      "communication-channel",
      "VERIFIED",
      true,
      "Daily order changes.",
    ),
    e(
      "rest-offline-kit",
      "Offline service kit",
      "recovery-mechanism",
      "STALE",
      true,
      "Paper checks and device instructions.",
      {
        lastVerifiedAt: "2026-03-03",
        verificationStatus: "STALE",
        documentationExists: true,
      },
    ),
    e(
      "rest-offline-doc",
      "Offline procedure",
      "document",
      "VERIFIED",
      true,
      "Printed in each manager office.",
      { storageLocationCategory: "physical-copy", documentationExists: true },
    ),
    e(
      "rest-location",
      "Harbor location",
      "location",
      "VERIFIED",
      true,
      "Highest-volume dining room.",
    ),
    e(
      "rest-service",
      "Run dinner service",
      "workflow",
      "VERIFIED",
      true,
      "Take orders, route tickets, and close checks.",
    ),
    e(
      "rest-close",
      "Close the day",
      "workflow",
      "DECLARED",
      true,
      "Reconcile checks and payment batches.",
    ),
    e(
      "rest-orders",
      "Place supplier order",
      "workflow",
      "VERIFIED",
      false,
      "Adjust next-day supplies.",
    ),
    e(
      "rest-guest-comms",
      "Notify waiting guests",
      "workflow",
      "UNKNOWN",
      false,
      "Send delay updates to guests.",
    ),
  ],
  relationships: [
    r(
      "re-r1",
      "rest-service",
      "rest-pos",
      "depends-on",
      "orders",
      "routes through",
    ),
    r(
      "re-r2",
      "rest-service",
      "rest-offline-kit",
      "depends-on",
      "orders",
      "can substitute with",
      "STALE",
    ),
    r(
      "re-r3",
      "rest-pos",
      "rest-payments",
      "depends-on",
      "payments",
      "authorizes through",
    ),
    r(
      "re-r4",
      "rest-offline-kit",
      "rest-offline-doc",
      "depends-on",
      "procedure",
      "uses",
    ),
    r(
      "re-r5",
      "rest-offline-kit",
      "rest-manager",
      "accessible-by",
      "knowledge",
      "rehearsed by",
    ),
    r(
      "re-r6",
      "rest-close",
      "rest-pos",
      "depends-on",
      "records",
      "reconciles in",
    ),
    r(
      "re-r7",
      "rest-orders",
      "rest-suppliers",
      "communicates-through",
      "inbox",
      "sends through",
    ),
    r(
      "re-r8",
      "rest-suppliers",
      "rest-manager",
      "accessible-by",
      "access",
      "owned by",
    ),
    r(
      "re-r9",
      "rest-guest-comms",
      "rest-reservations",
      "communicates-through",
      "guest-list",
      "sends through",
    ),
    r(
      "re-r10",
      "rest-location",
      "rest-floor",
      "administered-by",
      "management",
      "managed by",
    ),
    r(
      "re-r11",
      "rest-schedule",
      "rest-floor",
      "administered-by",
      "access",
      "managed by",
    ),
  ],
  scenarios: [
    s(
      "rest-pos-friday",
      "POS fails during dinner",
      ["rest-pos", "rest-manager"],
      1,
      "The POS is unavailable during the busiest service and the only manager who rehearsed the offline procedure is away.",
    ),
  ],
  proposals: [],
  activity: activity("restaurant"),
};

const charter: Workspace = {
  id: "demo-charter",
  slug: "meridian-charter",
  name: "Meridian",
  tagline: "One booking. One inbox. No handoff.",
  sector: "charter",
  fictional: true,
  cover: "/assets/demo-charter.webp",
  version: 1,
  entities: [
    e(
      "char-coordinator",
      "Ava Laurent",
      "person",
      "VERIFIED",
      true,
      "Primary booking coordinator.",
    ),
    e(
      "char-client-lead",
      "Jon Bell",
      "person",
      "DECLARED",
      false,
      "Client services lead.",
    ),
    e(
      "char-inbox",
      "Operations inbox",
      "communication-channel",
      "VERIFIED",
      true,
      "Vendor and customer correspondence.",
    ),
    e(
      "char-vendor",
      "Charter provider",
      "vendor",
      "DECLARED",
      true,
      "Fictional commercial service provider.",
    ),
    e(
      "char-confirmation",
      "Vendor confirmation",
      "document",
      "UNKNOWN",
      true,
      "Pending commercial confirmation. No flight-safety information.",
      {
        documentationExists: true,
        storageLocationCategory: "operations-inbox",
      },
    ),
    e(
      "char-crm",
      "Booking workspace",
      "service",
      "VERIFIED",
      true,
      "Customer request and service details.",
    ),
    e(
      "char-payment",
      "Payment link service",
      "service",
      "VERIFIED",
      true,
      "Commercial deposit collection.",
    ),
    e(
      "char-documents",
      "Customer documents",
      "document",
      "DECLARED",
      true,
      "Commercial booking documents only.",
    ),
    e(
      "char-phone",
      "Desk phone",
      "device",
      "VERIFIED",
      false,
      "Shared customer contact line.",
    ),
    e(
      "char-inquiry",
      "Qualify customer inquiry",
      "workflow",
      "VERIFIED",
      true,
      "Capture request and match a provider.",
    ),
    e(
      "char-booking",
      "Coordinate booking",
      "workflow",
      "VERIFIED",
      true,
      "Confirm provider, payment, and customer communication.",
    ),
    e(
      "char-customer-comms",
      "Update customer",
      "workflow",
      "VERIFIED",
      true,
      "Send the latest commercial status.",
    ),
    e(
      "char-vendor-comms",
      "Confirm vendor",
      "workflow",
      "DECLARED",
      true,
      "Obtain and record provider confirmation.",
    ),
  ],
  relationships: [
    r(
      "ch-r1",
      "char-inquiry",
      "char-crm",
      "depends-on",
      "record",
      "recorded in",
    ),
    r(
      "ch-r2",
      "char-inquiry",
      "char-inbox",
      "communicates-through",
      "inbox",
      "arrives through",
    ),
    r(
      "ch-r3",
      "char-booking",
      "char-confirmation",
      "depends-on",
      "confirmation",
      "requires",
    ),
    r(
      "ch-r4",
      "char-booking",
      "char-payment",
      "depends-on",
      "payment",
      "collects through",
    ),
    r(
      "ch-r5",
      "char-booking",
      "char-documents",
      "depends-on",
      "documents",
      "requires",
    ),
    r(
      "ch-r6",
      "char-confirmation",
      "char-inbox",
      "stored-in",
      "record",
      "stored in",
    ),
    r(
      "ch-r7",
      "char-vendor-comms",
      "char-inbox",
      "communicates-through",
      "inbox",
      "sends through",
    ),
    r(
      "ch-r8",
      "char-vendor-comms",
      "char-vendor",
      "communicates-through",
      "provider",
      "contacts",
    ),
    r(
      "ch-r9",
      "char-customer-comms",
      "char-inbox",
      "communicates-through",
      "inbox",
      "sends through",
    ),
    r(
      "ch-r10",
      "char-inbox",
      "char-coordinator",
      "accessible-by",
      "access",
      "managed by",
    ),
    r(
      "ch-r11",
      "char-phone",
      "char-client-lead",
      "accessible-by",
      "access",
      "answered by",
    ),
    r(
      "ch-r12",
      "char-crm",
      "char-client-lead",
      "administered-by",
      "access",
      "managed by",
    ),
  ],
  scenarios: [
    s(
      "char-coordinator-away",
      "Coordinator unavailable mid-booking",
      ["char-coordinator"],
      2,
      "A vendor confirmation and customer update both depend on the operations inbox while the booking coordinator is unavailable.",
    ),
  ],
  proposals: [],
  activity: activity("charter"),
};

function addStudioDepth() {
  appStudio.entities.push(
    e(
      "studio-engineering",
      "Kai Soto",
      "person",
      "VERIFIED",
      true,
      "Engineering lead and production fallback.",
    ),
    e(
      "studio-finance",
      "Nia Grant",
      "person",
      "DECLARED",
      false,
      "Finance and vendor operations owner.",
    ),
    e(
      "studio-qa",
      "Omar Reed",
      "person",
      "VERIFIED",
      false,
      "Quality lead for release rehearsals.",
    ),
    e(
      "studio-product-team",
      "Mobile product team",
      "team",
      "VERIFIED",
      true,
      "Engineers responsible for the three customer apps.",
    ),
    e(
      "studio-customer-db",
      "Customer database",
      "service",
      "VERIFIED",
      true,
      "Profiles, entitlements, and subscription state.",
    ),
    e(
      "studio-monitoring",
      "Production monitoring",
      "service",
      "VERIFIED",
      true,
      "Health checks and alert routing.",
    ),
    e(
      "studio-errors",
      "Error tracking",
      "vendor",
      "DECLARED",
      false,
      "Crash and release diagnostics.",
    ),
    e(
      "studio-payments",
      "Subscription payments",
      "vendor",
      "VERIFIED",
      true,
      "Customer subscription collection.",
    ),
    e(
      "studio-payout",
      "Payout account",
      "account",
      "DECLARED",
      true,
      "Receives platform and subscription payouts.",
    ),
    e(
      "studio-passwords",
      "Team password vault",
      "service",
      "STALE",
      true,
      "Shared operational credentials and recovery contacts.",
    ),
    e(
      "studio-registrar",
      "Domain registrar",
      "account",
      "VERIFIED",
      true,
      "Registration and DNS delegation controls.",
    ),
    e(
      "studio-qa-devices",
      "QA device set",
      "device",
      "VERIFIED",
      false,
      "Shared devices for release validation.",
    ),
    e(
      "studio-runbook",
      "Production recovery runbook",
      "document",
      "DECLARED",
      true,
      "Restoration sequence with owners and verification steps.",
    ),
    e(
      "studio-restore",
      "Restore production service",
      "workflow",
      "VERIFIED",
      true,
      "Diagnose, restore, verify, and communicate a production incident.",
    ),
    e(
      "studio-payout-workflow",
      "Reconcile subscription payouts",
      "workflow",
      "DECLARED",
      false,
      "Compare platform receipts with the finance account.",
    ),
    e(
      "studio-billing-team",
      "Billing operations team",
      "team",
      "DECLARED",
      true,
      "Owns refunds, payment recovery, invoicing, and month-end controls.",
    ),
    e(
      "studio-tax-service",
      "Tax and invoicing service",
      "vendor",
      "VERIFIED",
      false,
      "Calculates indirect tax and issues customer invoices.",
    ),
    e(
      "studio-refund-policy",
      "Refund authorization policy",
      "document",
      "VERIFIED",
      true,
      "Approval limits, evidence requirements, and escalation owners.",
    ),
    e(
      "studio-finance-channel",
      "Finance approvals channel",
      "communication-channel",
      "DECLARED",
      true,
      "Shared queue for refund and payout approvals.",
    ),
    e(
      "studio-billing-recovery",
      "Billing recovery account",
      "account",
      "STALE",
      true,
      "Break-glass access for payment configuration and webhook recovery.",
      { recoveryMethodExists: true, documentationExists: true },
    ),
    e(
      "studio-refund-workflow",
      "Process subscription refund",
      "workflow",
      "VERIFIED",
      true,
      "Validate entitlement, authorize, refund, notify, and record evidence.",
    ),
    e(
      "studio-billing-restore",
      "Restore customer billing",
      "workflow",
      "DECLARED",
      true,
      "Recover payment collection and reconcile subscription state after an outage.",
    ),
    e(
      "studio-month-close",
      "Close monthly finance",
      "workflow",
      "DECLARED",
      true,
      "Reconcile payouts, invoices, refunds, and unresolved payment exceptions.",
    ),
  );
  appStudio.relationships.push(
    r(
      "st-x1",
      "studio-product-team",
      "studio-engineering",
      "owned-by",
      "lead",
      "led by",
    ),
    r(
      "st-x2",
      "studio-release",
      "studio-product-team",
      "owned-by",
      "delivery",
      "delivered by",
    ),
    r(
      "st-x3",
      "studio-release",
      "studio-qa-devices",
      "depends-on",
      "quality",
      "verified on",
    ),
    r(
      "st-x4",
      "studio-restore",
      "studio-monitoring",
      "depends-on",
      "detection",
      "detected by",
    ),
    r(
      "st-x5",
      "studio-restore",
      "studio-customer-db",
      "depends-on",
      "data",
      "restores",
    ),
    r(
      "st-x6",
      "studio-restore",
      "studio-runbook",
      "depends-on",
      "procedure",
      "guided by",
    ),
    r(
      "st-x7",
      "studio-runbook",
      "studio-engineering",
      "accessible-by",
      "knowledge",
      "maintained by",
    ),
    r(
      "st-x8",
      "studio-monitoring",
      "studio-errors",
      "depends-on",
      "diagnostics",
      "correlates with",
    ),
    r(
      "st-x9",
      "studio-customer-db",
      "studio-host",
      "depends-on",
      "runtime",
      "runs on",
    ),
    r(
      "st-x10",
      "studio-dns",
      "studio-registrar",
      "administered-by",
      "registration",
      "delegated from",
    ),
    r(
      "st-x11",
      "studio-passwords",
      "studio-ops",
      "accessible-by",
      "access",
      "administered by",
    ),
    r(
      "st-x12",
      "studio-payout-workflow",
      "studio-payments",
      "depends-on",
      "receipts",
      "reconciles",
    ),
    r(
      "st-x13",
      "studio-payout-workflow",
      "studio-payout",
      "depends-on",
      "banking",
      "matches",
    ),
    r(
      "st-x14",
      "studio-payout",
      "studio-finance",
      "accessible-by",
      "access",
      "managed by",
    ),
    r(
      "st-x15",
      "studio-engineering",
      "studio-founder",
      "substitutes-for",
      "delegation",
      "release fallback",
      "DECLARED",
    ),
    r(
      "st-x16",
      "studio-billing-team",
      "studio-finance",
      "owned-by",
      "finance",
      "led by",
    ),
    r(
      "st-x17",
      "studio-refund-workflow",
      "studio-payments",
      "depends-on",
      "refund",
      "issues through",
    ),
    r(
      "st-x18",
      "studio-refund-workflow",
      "studio-customer-db",
      "depends-on",
      "entitlement",
      "validates in",
    ),
    r(
      "st-x19",
      "studio-refund-workflow",
      "studio-refund-policy",
      "required-by",
      "approval",
      "governed by",
    ),
    r(
      "st-x20",
      "studio-refund-workflow",
      "studio-billing-team",
      "owned-by",
      "owner",
      "owned by",
    ),
    r(
      "st-x21",
      "studio-refund-workflow",
      "studio-finance-channel",
      "communicates-through",
      "approval",
      "approved through",
    ),
    r(
      "st-x22",
      "studio-refund-policy",
      "studio-finance",
      "accessible-by",
      "policy-owner",
      "maintained by",
    ),
    r(
      "st-x23",
      "studio-finance-channel",
      "studio-finance",
      "accessible-by",
      "approver",
      "answered by",
    ),
    r(
      "st-x24",
      "studio-billing-restore",
      "studio-payments",
      "depends-on",
      "payment-runtime",
      "restores",
    ),
    r(
      "st-x25",
      "studio-billing-restore",
      "studio-customer-db",
      "depends-on",
      "subscription-state",
      "reconciles with",
    ),
    r(
      "st-x26",
      "studio-billing-restore",
      "studio-billing-recovery",
      "recovers-via",
      "break-glass",
      "uses",
    ),
    r(
      "st-x27",
      "studio-billing-recovery",
      "studio-passwords",
      "stored-in",
      "credential",
      "secured in",
      "STALE",
    ),
    r(
      "st-x28",
      "studio-billing-restore",
      "studio-billing-team",
      "owned-by",
      "owner",
      "owned by",
    ),
    r(
      "st-x29",
      "studio-month-close",
      "studio-payout-workflow",
      "depends-on",
      "payouts",
      "includes",
    ),
    r(
      "st-x30",
      "studio-month-close",
      "studio-tax-service",
      "depends-on",
      "invoicing",
      "matches invoices from",
    ),
    r(
      "st-x31",
      "studio-month-close",
      "studio-finance",
      "owned-by",
      "owner",
      "approved by",
    ),
    r(
      "st-x32",
      "studio-ops",
      "studio-finance",
      "substitutes-for",
      "finance-fallback",
      "finance fallback",
      "DECLARED",
    ),
  );
  appStudio.scenarios.push(
    s(
      "studio-founder-finance-away",
      "Founder and finance lead unavailable",
      ["studio-founder", "studio-finance"],
      5,
      "A release, a high-value refund, and month-end payout approval overlap while both approvers are unreachable.",
    ),
    s(
      "studio-billing-control-outage",
      "Payments and approvals unavailable",
      ["studio-payments", "studio-finance-channel"],
      2,
      "Customer billing must be restored and urgent refunds processed without the payment provider or approval queue.",
    ),
  );
}

function addEducationDepth() {
  edtech.entities.push(
    e(
      "edu-director",
      "Elena Ruiz",
      "person",
      "VERIFIED",
      true,
      "Program director and academic escalation owner.",
    ),
    e(
      "edu-instructor",
      "Marcus Lee",
      "person",
      "DECLARED",
      false,
      "Lead instructor and faculty delegate.",
    ),
    e(
      "edu-accessibility-owner",
      "Priya Shah",
      "person",
      "VERIFIED",
      false,
      "Accessibility and accommodations lead.",
    ),
    e(
      "edu-faculty",
      "Teaching faculty",
      "team",
      "VERIFIED",
      true,
      "Instructors delivering scheduled cohorts.",
    ),
    e(
      "edu-recordings",
      "Course recording library",
      "service",
      "VERIFIED",
      false,
      "Recorded lessons and course archives.",
    ),
    e(
      "edu-grades",
      "Grade records",
      "service",
      "VERIFIED",
      true,
      "Assessment results and completion evidence.",
    ),
    e(
      "edu-enrollment",
      "Enrollment system",
      "service",
      "DECLARED",
      true,
      "Learner enrollment and seat assignment.",
    ),
    e(
      "edu-accessibility",
      "Accessibility support",
      "workflow",
      "VERIFIED",
      true,
      "Deliver accommodations during assessments.",
    ),
    e(
      "edu-schedule",
      "Faculty schedule",
      "document",
      "VERIFIED",
      true,
      "Live teaching and coverage roster.",
    ),
    e(
      "edu-backup-laptop",
      "Break-glass laptop",
      "device",
      "STALE",
      true,
      "Offline administrator device stored in the office.",
    ),
    e(
      "edu-transcripts",
      "Transcript archive",
      "document",
      "DECLARED",
      false,
      "Completion and transcript exports.",
    ),
    e(
      "edu-notifications",
      "Learner notification service",
      "communication-channel",
      "VERIFIED",
      true,
      "Time-sensitive learner messages.",
    ),
    e(
      "edu-refunds",
      "Process learner refund",
      "workflow",
      "DECLARED",
      false,
      "Validate enrollment and issue a refund.",
    ),
    e(
      "edu-record",
      "Record a live class",
      "workflow",
      "VERIFIED",
      false,
      "Capture, process, and publish a session.",
    ),
  );
  edtech.relationships.push(
    r("ed-x1", "edu-faculty", "edu-director", "owned-by", "lead", "led by"),
    r(
      "ed-x2",
      "edu-instructor",
      "edu-director",
      "substitutes-for",
      "delegation",
      "academic fallback",
      "DECLARED",
    ),
    r("ed-x3", "edu-exam", "edu-grades", "depends-on", "records", "writes to"),
    r(
      "ed-x4",
      "edu-exam",
      "edu-enrollment",
      "depends-on",
      "roster",
      "reads roster from",
    ),
    r(
      "ed-x5",
      "edu-accessibility",
      "edu-accessibility-owner",
      "owned-by",
      "owner",
      "owned by",
    ),
    r(
      "ed-x6",
      "edu-accessibility",
      "edu-lms",
      "depends-on",
      "delivery",
      "configured in",
    ),
    r(
      "ed-x7",
      "edu-schedule",
      "edu-director",
      "accessible-by",
      "planning",
      "maintained by",
    ),
    r(
      "ed-x8",
      "edu-emergency",
      "edu-backup-laptop",
      "recovers-via",
      "device",
      "available on",
    ),
    r(
      "ed-x9",
      "edu-record",
      "edu-video",
      "depends-on",
      "capture",
      "captured with",
    ),
    r(
      "ed-x10",
      "edu-record",
      "edu-recordings",
      "depends-on",
      "storage",
      "published to",
    ),
    r(
      "ed-x11",
      "edu-refunds",
      "edu-enrollment",
      "depends-on",
      "records",
      "validates in",
    ),
    r(
      "ed-x12",
      "edu-student-help",
      "edu-notifications",
      "communicates-through",
      "outbound",
      "updates through",
    ),
    r(
      "ed-x13",
      "edu-transcripts",
      "edu-grades",
      "depends-on",
      "results",
      "generated from",
    ),
  );
  edtech.scenarios.push(
    s(
      "edu-recording-delay",
      "Lead instructor misses a live cohort",
      ["edu-instructor"],
      2,
      "A live cohort and recording both need alternate faculty coverage.",
    ),
  );
}

function addHospitalityDepth() {
  restaurant.entities.push(
    e(
      "rest-owner",
      "Sofia Marin",
      "person",
      "VERIFIED",
      true,
      "Group owner and banking approver.",
    ),
    e(
      "rest-chef",
      "Elias Hart",
      "person",
      "VERIFIED",
      true,
      "Executive chef and supplier escalation owner.",
    ),
    e(
      "rest-bar",
      "Mae Kim",
      "person",
      "DECLARED",
      false,
      "Bar lead and closing fallback.",
    ),
    e(
      "rest-kitchen",
      "Kitchen team",
      "team",
      "VERIFIED",
      true,
      "Cooks and pass coordination.",
    ),
    e(
      "rest-inventory",
      "Inventory records",
      "service",
      "VERIFIED",
      true,
      "Ingredient counts and order thresholds.",
    ),
    e(
      "rest-payroll",
      "Payroll service",
      "vendor",
      "VERIFIED",
      true,
      "Payroll calculations and disbursement.",
    ),
    e(
      "rest-safe",
      "Cash safe",
      "location",
      "VERIFIED",
      true,
      "Physical close packets and cash deposits.",
    ),
    e(
      "rest-fridge",
      "Refrigeration monitor",
      "device",
      "VERIFIED",
      true,
      "Temperature alerts for cold storage.",
    ),
    e(
      "rest-food-safety",
      "Food safety log",
      "document",
      "DECLARED",
      true,
      "Temperature and sanitation checks.",
    ),
    e(
      "rest-utilities",
      "Site utility controls",
      "service",
      "UNKNOWN",
      true,
      "Electric, gas, and refrigeration controls.",
    ),
    e(
      "rest-payroll-run",
      "Run weekly payroll",
      "workflow",
      "VERIFIED",
      true,
      "Approve hours and release payroll.",
    ),
    e(
      "rest-stock",
      "Replenish critical stock",
      "workflow",
      "DECLARED",
      true,
      "Review counts and confirm supplier delivery.",
    ),
    e(
      "rest-safety",
      "Respond to cold-storage alert",
      "workflow",
      "VERIFIED",
      true,
      "Protect stock and document temperatures.",
    ),
    e(
      "rest-booking-tablet",
      "Host stand tablet",
      "device",
      "VERIFIED",
      false,
      "Reservations and guest messaging at the door.",
    ),
  );
  restaurant.relationships.push(
    r("re-x1", "rest-kitchen", "rest-chef", "owned-by", "lead", "led by"),
    r(
      "re-x2",
      "rest-bar",
      "rest-manager",
      "substitutes-for",
      "delegation",
      "closing fallback",
      "DECLARED",
    ),
    r(
      "re-x3",
      "rest-payroll-run",
      "rest-payroll",
      "depends-on",
      "payroll",
      "processed by",
    ),
    r(
      "re-x4",
      "rest-payroll-run",
      "rest-schedule",
      "depends-on",
      "hours",
      "reads hours from",
    ),
    r(
      "re-x5",
      "rest-payroll",
      "rest-owner",
      "accessible-by",
      "approval",
      "approved by",
    ),
    r(
      "re-x6",
      "rest-stock",
      "rest-inventory",
      "depends-on",
      "counts",
      "reads from",
    ),
    r(
      "re-x7",
      "rest-stock",
      "rest-suppliers",
      "communicates-through",
      "order",
      "orders through",
    ),
    r(
      "re-x8",
      "rest-inventory",
      "rest-chef",
      "administered-by",
      "owner",
      "managed by",
    ),
    r(
      "re-x9",
      "rest-safety",
      "rest-fridge",
      "depends-on",
      "alert",
      "triggered by",
    ),
    r(
      "re-x10",
      "rest-safety",
      "rest-food-safety",
      "depends-on",
      "records",
      "recorded in",
    ),
    r(
      "re-x11",
      "rest-fridge",
      "rest-utilities",
      "depends-on",
      "power",
      "powered by",
    ),
    r(
      "re-x12",
      "rest-close",
      "rest-safe",
      "depends-on",
      "cash",
      "deposited in",
    ),
    r(
      "re-x13",
      "rest-reservations",
      "rest-booking-tablet",
      "accessible-by",
      "device",
      "available on",
    ),
  );
  restaurant.scenarios.push(
    s(
      "rest-cold-storage",
      "Cold storage alert before service",
      ["rest-fridge", "rest-chef"],
      1,
      "Cold storage needs triage while the executive chef is unavailable.",
    ),
  );
}

function addCharterDepth() {
  charter.entities.push(
    e(
      "char-director",
      "Dominic Hayes",
      "person",
      "VERIFIED",
      true,
      "Operations director and commercial approver.",
    ),
    e(
      "char-dispatch",
      "Leila Noor",
      "person",
      "VERIFIED",
      true,
      "Dispatcher and coordinator fallback.",
    ),
    e(
      "char-maintenance-owner",
      "Rafael Costa",
      "person",
      "DECLARED",
      false,
      "Maintenance coordination contact.",
    ),
    e(
      "char-ops-team",
      "Operations desk",
      "team",
      "VERIFIED",
      true,
      "Commercial coordination and customer updates.",
    ),
    e(
      "char-schedule",
      "Flight schedule",
      "service",
      "VERIFIED",
      true,
      "Planned commercial movements and changes.",
    ),
    e(
      "char-roster",
      "Crew roster",
      "document",
      "VERIFIED",
      true,
      "Availability and duty coordination.",
    ),
    e(
      "char-weather",
      "Weather planning",
      "vendor",
      "DECLARED",
      true,
      "Planning information for commercial coordination.",
    ),
    e(
      "char-maintenance",
      "Maintenance records",
      "document",
      "VERIFIED",
      true,
      "Commercial availability records from the provider.",
    ),
    e(
      "char-fuel",
      "Fuel coordination",
      "vendor",
      "DECLARED",
      false,
      "Provider fuel coordination contact.",
    ),
    e(
      "char-satphone",
      "Operations satellite phone",
      "device",
      "STALE",
      true,
      "Alternate operations contact device.",
    ),
    e(
      "char-backup",
      "Dispatch backup laptop",
      "device",
      "VERIFIED",
      true,
      "Independent access for the second dispatcher.",
    ),
    e(
      "char-procedure",
      "Disruption response guide",
      "document",
      "VERIFIED",
      true,
      "Customer, provider, and internal handoff sequence.",
    ),
    e(
      "char-disruption",
      "Coordinate a disrupted booking",
      "workflow",
      "VERIFIED",
      true,
      "Replan provider coordination and customer updates.",
    ),
    e(
      "char-crew-change",
      "Coordinate crew change",
      "workflow",
      "DECLARED",
      true,
      "Confirm alternate crew and update stakeholders.",
    ),
    e(
      "char-reporting",
      "Reconcile completed booking",
      "workflow",
      "VERIFIED",
      false,
      "Close commercial records and supplier costs.",
    ),
  );
  charter.relationships.push(
    r("ch-x1", "char-ops-team", "char-director", "owned-by", "lead", "led by"),
    r(
      "ch-x2",
      "char-dispatch",
      "char-coordinator",
      "substitutes-for",
      "delegation",
      "booking fallback",
      "VERIFIED",
    ),
    r(
      "ch-x3",
      "char-disruption",
      "char-schedule",
      "depends-on",
      "schedule",
      "updates",
    ),
    r(
      "ch-x4",
      "char-disruption",
      "char-procedure",
      "depends-on",
      "procedure",
      "guided by",
    ),
    r(
      "ch-x5",
      "char-disruption",
      "char-satphone",
      "communicates-through",
      "alternate-contact",
      "can use",
    ),
    r(
      "ch-x6",
      "char-schedule",
      "char-dispatch",
      "administered-by",
      "access",
      "managed by",
    ),
    r(
      "ch-x7",
      "char-crew-change",
      "char-roster",
      "depends-on",
      "availability",
      "reads",
    ),
    r(
      "ch-x8",
      "char-crew-change",
      "char-weather",
      "depends-on",
      "planning",
      "checks",
    ),
    r(
      "ch-x9",
      "char-roster",
      "char-director",
      "accessible-by",
      "approval",
      "approved by",
    ),
    r(
      "ch-x10",
      "char-maintenance",
      "char-maintenance-owner",
      "accessible-by",
      "records",
      "coordinated by",
    ),
    r(
      "ch-x11",
      "char-reporting",
      "char-crm",
      "depends-on",
      "record",
      "closes in",
    ),
    r(
      "ch-x12",
      "char-reporting",
      "char-payment",
      "depends-on",
      "payment",
      "reconciles",
    ),
    r(
      "ch-x13",
      "char-backup",
      "char-dispatch",
      "accessible-by",
      "device",
      "assigned to",
    ),
    r(
      "ch-x14",
      "char-vendor",
      "char-fuel",
      "depends-on",
      "fuel",
      "coordinates with",
    ),
  );
  charter.scenarios.push(
    s(
      "char-disruption-weekend",
      "Weekend disruption with inbox unavailable",
      ["char-inbox", "char-coordinator"],
      1,
      "A booking changes after hours and the normal inbox and coordinator are unavailable.",
    ),
  );
}

const roleById: Record<string, string> = {
  "studio-founder": "Founder & product owner",
  "studio-ops": "Operations lead",
  "studio-support-owner": "Customer support lead",
  "studio-engineering": "Engineering lead",
  "studio-finance": "Finance & vendor operations",
  "studio-qa": "Quality lead",
  "edu-ops": "Operations lead",
  "edu-support": "Student support coordinator",
  "edu-director": "Program director",
  "edu-instructor": "Lead instructor",
  "edu-accessibility-owner": "Accessibility lead",
  "rest-manager": "General manager",
  "rest-floor": "Floor lead",
  "rest-owner": "Group owner",
  "rest-chef": "Executive chef",
  "rest-bar": "Bar lead",
  "char-coordinator": "Booking coordinator",
  "char-client-lead": "Client services lead",
  "char-director": "Operations director",
  "char-dispatch": "Dispatcher",
  "char-maintenance-owner": "Maintenance coordinator",
};

type DemoSector = Exclude<Workspace["sector"], "custom">;
type DemoAsset = readonly [sector: DemoSector, index: number];

// Every assignment below was checked against the generated contact sheets.
// Keeping it explicit prevents entity order changes from silently putting a
// laptop on a person, a portrait on a service, or an office on a device.
export const demoAssetByEntityId: Record<string, DemoAsset> = {
  "studio-founder": ["studio", 21],
  "studio-ops": ["studio", 1],
  "studio-support-owner": ["studio", 8],
  "studio-phone": ["studio", 3],
  "studio-apple-account": ["studio", 12],
  "studio-appstore": ["studio", 14],
  "studio-cert": ["studio", 11],
  "studio-github": ["studio", 2],
  "studio-ci": ["studio", 22],
  "studio-host": ["studio", 6],
  "studio-dns": ["studio", 7],
  "studio-support": ["studio", 12],
  "studio-status": ["studio", 16],
  "studio-recovery-doc": ["studio", 19],
  "studio-release": ["studio", 4],
  "studio-support-workflow": ["studio", 12],
  "studio-incident": ["studio", 16],
  "studio-engineering": ["studio", 24],
  "studio-finance": ["studio", 23],
  "studio-qa": ["education", 4],
  "studio-product-team": ["studio", 18],
  "studio-customer-db": ["studio", 5],
  "studio-monitoring": ["studio", 13],
  "studio-errors": ["studio", 14],
  "studio-payments": ["studio", 17],
  "studio-payout": ["studio", 9],
  "studio-passwords": ["studio", 10],
  "studio-registrar": ["studio", 7],
  "studio-qa-devices": ["studio", 3],
  "studio-runbook": ["studio", 19],
  "studio-restore": ["studio", 13],
  "studio-payout-workflow": ["studio", 9],
  "studio-billing-team": ["studio", 18],
  "studio-tax-service": ["studio", 9],
  "studio-refund-policy": ["studio", 19],
  "studio-finance-channel": ["studio", 9],
  "studio-billing-recovery": ["studio", 11],
  "studio-refund-workflow": ["studio", 17],
  "studio-billing-restore": ["studio", 6],
  "studio-month-close": ["studio", 9],

  "edu-ops": ["education", 1],
  "edu-support": ["education", 4],
  "edu-sso": ["education", 13],
  "edu-lms": ["education", 8],
  "edu-content": ["education", 21],
  "edu-video": ["education", 7],
  "edu-admin": ["education", 9],
  "edu-emergency": ["education", 23],
  "edu-procedure": ["education", 14],
  "edu-billing": ["education", 22],
  "edu-exam": ["education", 17],
  "edu-teacher-help": ["education", 19],
  "edu-student-help": ["education", 10],
  "edu-support-inbox": ["education", 20],
  "edu-director": ["education", 3],
  "edu-instructor": ["education", 2],
  "edu-accessibility-owner": ["education", 5],
  "edu-faculty": ["education", 25],
  "edu-recordings": ["education", 12],
  "edu-grades": ["education", 16],
  "edu-enrollment": ["education", 8],
  "edu-accessibility": ["education", 18],
  "edu-schedule": ["education", 17],
  "edu-backup-laptop": ["education", 23],
  "edu-transcripts": ["education", 15],
  "edu-notifications": ["education", 6],
  "edu-refunds": ["education", 22],
  "edu-record": ["education", 7],

  "rest-manager": ["hospitality", 1],
  "rest-floor": ["hospitality", 2],
  "rest-pos": ["hospitality", 8],
  "rest-payments": ["hospitality", 15],
  "rest-reservations": ["hospitality", 20],
  "rest-schedule": ["hospitality", 22],
  "rest-suppliers": ["hospitality", 10],
  "rest-offline-kit": ["hospitality", 14],
  "rest-offline-doc": ["hospitality", 13],
  "rest-location": ["hospitality", 6],
  "rest-service": ["hospitality", 7],
  "rest-close": ["hospitality", 25],
  "rest-orders": ["hospitality", 11],
  "rest-guest-comms": ["hospitality", 21],
  "rest-owner": ["hospitality", 3],
  "rest-chef": ["hospitality", 4],
  "rest-bar": ["hospitality", 5],
  "rest-kitchen": ["hospitality", 7],
  "rest-inventory": ["hospitality", 11],
  "rest-payroll": ["hospitality", 12],
  "rest-safe": ["hospitality", 16],
  "rest-fridge": ["hospitality", 17],
  "rest-food-safety": ["hospitality", 18],
  "rest-utilities": ["hospitality", 24],
  "rest-payroll-run": ["hospitality", 25],
  "rest-stock": ["hospitality", 10],
  "rest-safety": ["hospitality", 17],
  "rest-booking-tablet": ["hospitality", 20],

  "char-coordinator": ["charter", 2],
  "char-client-lead": ["charter", 1],
  "char-inbox": ["charter", 9],
  "char-vendor": ["charter", 6],
  "char-confirmation": ["charter", 12],
  "char-crm": ["charter", 7],
  "char-payment": ["charter", 15],
  "char-documents": ["charter", 12],
  "char-phone": ["charter", 17],
  "char-inquiry": ["charter", 16],
  "char-booking": ["charter", 8],
  "char-customer-comms": ["charter", 16],
  "char-vendor-comms": ["charter", 9],
  "char-director": ["education", 2],
  "char-dispatch": ["charter", 4],
  "char-maintenance-owner": ["charter", 5],
  "char-ops-team": ["charter", 22],
  "char-schedule": ["charter", 8],
  "char-roster": ["charter", 10],
  "char-weather": ["charter", 11],
  "char-maintenance": ["charter", 13],
  "char-fuel": ["charter", 14],
  "char-satphone": ["charter", 17],
  "char-backup": ["charter", 18],
  "char-procedure": ["charter", 20],
  "char-disruption": ["charter", 25],
  "char-crew-change": ["charter", 22],
  "char-reporting": ["charter", 15],
};

const nodeImage = ([sector, index]: DemoAsset) =>
  `/assets/nodes/${sector}/${String(index).padStart(2, "0")}.webp`;

const reviewedAssetPools: Record<Entity["type"], DemoAsset[]> = {
  person: [
    ["studio", 1],
    ["studio", 8],
    ["studio", 21],
    ["studio", 23],
    ["studio", 24],
    ["education", 1],
    ["education", 2],
    ["education", 3],
    ["education", 4],
    ["education", 5],
    ["hospitality", 1],
    ["hospitality", 2],
    ["hospitality", 3],
    ["hospitality", 4],
    ["hospitality", 5],
    ["charter", 1],
    ["charter", 2],
    ["charter", 4],
    ["charter", 5],
  ],
  team: [
    ["studio", 18],
    ["education", 25],
    ["charter", 22],
  ],
  service: [
    ["studio", 5],
    ["studio", 6],
    ["studio", 7],
    ["studio", 13],
    ["education", 8],
    ["education", 12],
    ["hospitality", 8],
    ["hospitality", 11],
    ["charter", 7],
    ["charter", 10],
  ],
  vendor: [
    ["studio", 14],
    ["studio", 17],
    ["hospitality", 10],
    ["hospitality", 15],
    ["hospitality", 24],
    ["charter", 6],
    ["charter", 14],
  ],
  device: [
    ["studio", 3],
    ["education", 23],
    ["hospitality", 17],
    ["hospitality", 20],
    ["charter", 17],
    ["charter", 18],
  ],
  document: [
    ["studio", 19],
    ["education", 14],
    ["education", 15],
    ["hospitality", 13],
    ["charter", 12],
    ["charter", 20],
  ],
  account: [
    ["studio", 9],
    ["studio", 11],
    ["studio", 12],
    ["education", 9],
    ["charter", 15],
  ],
  workflow: [
    ["studio", 4],
    ["studio", 13],
    ["education", 18],
    ["education", 22],
    ["hospitality", 7],
    ["hospitality", 25],
    ["charter", 25],
  ],
  location: [
    ["hospitality", 6],
    ["hospitality", 16],
  ],
  "communication-channel": [
    ["studio", 16],
    ["education", 6],
    ["education", 20],
    ["hospitality", 21],
    ["charter", 9],
    ["charter", 16],
  ],
  "recovery-mechanism": [
    ["studio", 10],
    ["studio", 11],
    ["hospitality", 14],
    ["hospitality", 17],
    ["charter", 17],
    ["charter", 18],
  ],
};

export function reviewedAssetForType(type: Entity["type"], index = 0) {
  const pool = reviewedAssetPools[type];
  return nodeImage(pool[index % pool.length]!);
}

function decorate(workspace: Workspace) {
  workspace.seedRevision = 2;
  workspace.entities = workspace.entities.map((entity) => {
    const assignedAsset = demoAssetByEntityId[entity.id];
    if (!assignedAsset)
      throw new Error(`Missing reviewed demo asset for ${entity.id}.`);
    return {
      ...entity,
      image: nodeImage(assignedAsset),
      role:
        roleById[entity.id] ??
        (entity.type === "workflow"
          ? "Operational workflow"
          : entity.type.replaceAll("-", " ")),
      ...(entity.type === "person"
        ? {
            team:
              workspace.sector === "hospitality"
                ? "Operations"
                : workspace.sector === "education"
                  ? "Learning operations"
                  : "Continuity team",
          }
        : {}),
    };
  });
}

addStudioDepth();
addEducationDepth();
addHospitalityDepth();
addCharterDepth();
for (const workspace of [appStudio, edtech, restaurant, charter])
  decorate(workspace);

export const demoWorkspaces = [appStudio, edtech, restaurant, charter] as const;

export function cloneDemo(slug: string): Workspace | undefined {
  const workspace = demoWorkspaces.find((candidate) => candidate.slug === slug);
  return workspace ? structuredClone(workspace) : undefined;
}
